### ISSUE TITLE
pz_split_llstr_string compiler warning

### ISSUE THREAD

**Issue by sckott** [ropensci/parzer#26] opened 2020-07-14 18:20 UTC
Getting compiler warning on Windows for this method, see https://github.com/ropensci/parzer/runs/870437962?check_suite_focus=true#step:11:76 

```
pz_split_llstr.cpp:19:69: warning: suggest parentheses around comparison in operand of '|' [-Wparentheses]
   } else if (nbCommas == 0 && nbSpaces == 1 && nbSC == 0 && (nbDots == 0 | nbDots == 2)) {
                                                              ~~~~~~~^~~~
```

I tried to just put another set of parens around the existing parens i.e., `((nbDots == 0 | nbDots == 2))` , but that didn't work, not sure what the problem is

ping @AlbanSagouis 

p.s., switched to using github actions, you can find checks at https://github.com/ropensci/parzer/actions?query=workflow%3AR-check

**Comment by AlbanSagouis** [comment] 2020-07-15 08:43
Hi @sckott 
Yes, I had this warning when checking too but I couldn't see how to solve it and the script was compiling and working as intended so I committed anyway.

Now that I had an other look, I thought the issue was not with the parens but with the `|`, there should be 2 and there was only one, my bad. I just pushed a commit solving it.

**Comment by sckott** [comment] 2020-07-15 16:07
Thanks!

**Closed** 2020-07-15 16:07 UTC

**Comment by AlbanSagouis** [comment] 2020-07-16 06:11
Hi @sckott 
The modification was so small that I wonder. What would have been best practice between writing a comment with the modified line of code included and clear info on where it should go OR modifying the code in my repo and then requesting a pull request?

**Comment by sckott** [comment] 2020-07-16 16:18
> writing a comment 

does that mean opening an issue?

If the question is: "open an issue or PR" - I'd say open an issue first unless the change is sufficiently small OR if it's larger but doesn't touch code (e.g, if you add documentation only or make a change to a non-code file).  

In this case there was an issue already open (this one). 

For any code changes, I always locally run tests and R check to make sure no problems were introduced, and then CI will do that too after pushing up. Additionally, for any code changes that there isn't currently a test for, ideally add a new test

**Comment by AlbanSagouis** [comment] 2020-07-17 08:08
By 'writing a comment', I meant sending you a message on the page of this already opened issue and just paste the modified line of code.

Thanks for the advice!

**Comment by sckott** [comment] 2020-07-17 17:56
Ah, yes, you can definitely do that
